<?php
 /**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * @category   design_default
 * @package    PersianMagento_Enpayment
 * @copyright  Copyright (c) 1392-2013 Persian Magento . (http://www.persian-magento.ir)
 */ 
?>
<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
			<?php echo $this->__('You will be redirected to En website when you place an order.') ?>
        </li>
		<div style="padding:10px 15px 15px;">
			<img src="<?php echo $this->getPaymentImageSrc(); ?>" alt="<?php echo $this->__('En payment methods') ?>" />
        </div>
    </ul>
</fieldset>